spring:
  application.name: post-service

  datasource:
    url: jdbc:h2:file:./db/algaworks-posts-post-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: '123'

  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch: 4